FROM fedora:23
MAINTAINER "André Martins <aanm90@gmail.com>"
RUN dnf -y update && \
dnf -y install openvswitch tcpdump sudo && \
dnf clean all && \
systemctl disable openvswitch.service
ADD . /opt/cilium
WORKDIR /opt/cilium
RUN mv cilium-Linux-x86_64 /usr/bin/cilium
ENV PIPEWORK /opt/cilium/backend/pipework
ENV ADD_ENDPOINT /opt/cilium/backend/add-endpoint.sh
ENV REMOVE_ENDPOINT /opt/cilium/backend/remove-endpoint.sh
ENTRYPOINT ["cilium"]
