FROM golang:1.5
MAINTAINER "André Martins <aanm90@gmail.com>"
RUN go get github.com/tools/godep
ADD Godeps /go/src/github.com/cilium-team/cilium/Godeps
ADD cilium /go/src/github.com/cilium-team/cilium/cilium
WORKDIR /go/src/github.com/cilium-team/cilium
RUN godep go test ./cilium/...
RUN godep go build -o cilium-Linux-x86_64 ./cilium/cilium.go
