FROM golang:1.5
MAINTAINER "André Martins <aanm90@gmail.com>"
ADD . /go/src/github.com/cilium-team/cilium
ENV GOPATH /go/src:/go/src/github.com/cilium-team/cilium/Godeps/_workspace:$GOPATH
WORKDIR /go/src/github.com/cilium-team/cilium
RUN go test ./cilium/...
RUN go build -o cilium-Linux-x86_64 ./cilium/cilium.go
