#!/bin/bash

echo "build-images              Pulls and creates all necessary docker images"
echo "                          used by a cilium node inside 'images/'"
echo "                          directory."
echo ""
echo "cilium-binary             Builds the cilium binary inside docker and"
echo "                          copies the binary to the root's project."
echo ""
echo "cilium-images             Builds cilium's docker image with the tag"
echo "                          'latest'."
echo ""
echo "cilium                    Produces the cilium binary."
echo ""
echo "clean-containers          Cleans all containers with that have the name"
echo "                          'cilium' in the node that is executed."
echo ""
echo "clean-images              Deletes all images that are inside 'images/'"
echo "                          directory."
echo ""
echo "clean-swarm-vms           Stop and deletes all vagrant VMs created by"
echo "                          this project (node1 and node2)."
echo ""
echo "import-images             Imports all images inside 'images/' to the"
echo "                          current host. Essentially used by the nodes"
echo "                          when redeploying images."
echo ""
echo "infect                    Cilium's infection in the current node."
echo ""
echo "redeploy-cilium-image     Re-deploys the cilium docker image under"
echo "                          'images/' directory inside vagrant node1 and"
echo "                          vagrant node2."
echo ""
echo "redeploy-images           Re-deploys all docker images under 'images/'"
echo "                          (including cilium image inside vagrant node1"
echo "                          and vagrant node2."
echo ""
echo "refresh-policy            Cleans and put all policies inside 'policy/'"
echo "                          directory in the ElasticSearch container."
echo ""
echo "reset-cluster             Cleans all containers from host, vagrant node1"
echo "                          and vagrant node2 and starts again all cilium's"
echo "                          components in this private cluster."
echo ""
echo "run-kibana                Runs a Kibana container, useful to see some"
echo "                          data graphs."
echo ""
echo "setup-vagrant-machines    Creates and setups all vagrant nodes necessary"
echo "                          for development (node1 and node2)."
echo ""
echo "shell                     Debug container used to debug possible network"
echo "                          problems inside the development and application"
echo "                          network created by cilium."
echo ""
echo "tests                     Performs cilium's unit tests."
echo ""
echo "update-godeps             Useful to update all Godeps inside the 'Godeps'"
echo "                          directory."